@startuml

skinparam componentStyle uml2
actor User
actor Admin
database PostgresMovieData
database PostgresAuthData
database ElasticSearch
component AdminPanel
component LoadBalancer
component API
component Auth
component ETL

User -right-> LoadBalancer: Запрос на просмотр контента
LoadBalancer -right-> API: Запрос данных
API -right-> Auth: Запрос на аутентификацию/авторизацию пользователя
API -down-> ElasticSearch
Auth -right-> PostgresAuthData
PostgresMovieData -up-> ETL
ETL -down-> PostgresMovieData
ETL -up-> ElasticSearch
Admin -left-> AdminPanel: Редактирование данных
AdminPanel -left-> PostgresMovieData

@enduml
