@startuml

skinparam componentStyle uml2
actor User
actor Admin
database PostgresMovieData
database PostgresAuthData
database ElasticSearch
database OLAP
database Kafka
component AdminPanel
component LoadBalancer
component TokenValidator
component API
component Auth
component ETL
component DataAnalysisETL

User -right-> LoadBalancer: Запрос на просмотр контента
LoadBalancer -right-> API: Запрос данных
API -right-> Auth: Запрос на аутентификацию/авторизацию пользователя
LoadBalancer -down-> TokenValidator
TokenValidator -down-> Kafka : Запись событий пользователей
Kafka -down-> DataAnalysisETL
DataAnalysisETL -down->OLAP
API -down-> ElasticSearch
Auth -right-> PostgresAuthData
PostgresMovieData -up-> ETL
ETL -down-> PostgresMovieData
ETL -up-> ElasticSearch
Admin -left-> AdminPanel: Редактирование данных
AdminPanel -up-> PostgresMovieData

@enduml
